"""Build dataclasses from responses exposed by the D&D 5e API.

Examples:
	python -m api.build_importer
	python -m api.build_importer --endpoint monsters --include-details
	python -m api.build_importer --endpoint monsters/goblin
"""

from __future__ import annotations

import argparse
import keyword
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urljoin, urlparse

import requests

URL_BASE = "https://www.dnd5eapi.co/api/2014/"
DEFAULT_OUTPUT = Path(__file__).with_name("generated_dnd5e.py")
GEN_WARNING = "# This file is auto-generated by api.build_importer. Do not edit manually.\n"


@dataclass
class ClassDefinition:
	name: str
	fields: list[tuple[str, str, str]]


class DataclassBuilder:
	"""Collect dataclasses while recursively walking JSON values."""

	def __init__(self) -> None:
		self.definitions: list[ClassDefinition] = []
		self._names: set[str] = set()

	def add_value(self, class_name: str, value: Any) -> str:
		if isinstance(value, dict):
			return self.add_dict(class_name, value)
		if isinstance(value, list):
			return self.type_for_list(class_name, value)
		return primitive_type(value)

	def add_dict(self, class_name: str, value: dict[str, Any]) -> str:
		class_name = unique_class_name(class_name, self._names)
		self._names.add(class_name)
		definition = ClassDefinition(class_name, [])
		self.definitions.append(definition)

		for key, child in value.items():
			field_name = safe_field_name(key)
			child_name = f"{class_name}{pascal_case(key)}"
			definition.fields.append((field_name, self.add_value(child_name, child), key))
		return class_name

	def type_for_list(self, class_name: str, values: list[Any]) -> str:
		if not values:
			return "list[Any]"
		first_type = self.add_value(f"{class_name}Item", values[0])
		if all(type(value) is type(values[0]) for value in values):
			return f"list[{first_type}]"
		return "list[Any]"


def primitive_type(value: Any) -> str:
	if value is None:
		return "Any"
	if isinstance(value, bool):
		return "bool"
	if isinstance(value, int):
		return "int"
	if isinstance(value, float):
		return "float"
	if isinstance(value, str):
		return "str"
	return "Any"


def pascal_case(value: str) -> str:
	words = re.findall(r"[A-Za-z0-9]+", value)
	result = "".join(word[:1].upper() + word[1:] for word in words)
	return result or "Value"


def safe_field_name(value: str) -> str:
	name = re.sub(r"\W", "_", value)
	if not name or name[0].isdigit() or keyword.iskeyword(name):
		name = f"{name}_"
	return name


def unique_class_name(name: str, used: set[str]) -> str:
	candidate = pascal_case(name)
	suffix = 2
	while candidate in used:
		candidate = f"{pascal_case(name)}{suffix}"
		suffix += 1
	return candidate


def absolute_url(endpoint: str) -> str:
	if endpoint.startswith("http"):
		return endpoint
	if endpoint.startswith("/"):
		parsed = urlparse(URL_BASE)
		return urljoin(f"{parsed.scheme}://{parsed.netloc}", endpoint)
	return urljoin(URL_BASE, endpoint)


def fetch_json(session: requests.Session, endpoint: str) -> Any:
	url = absolute_url(endpoint)
	response = session.get(url, headers={"Accept": "application/json"}, timeout=30)
	response.raise_for_status()
	return response.json()


def endpoint_name(endpoint: str) -> str:
	parts = [part for part in urlparse(endpoint).path.split("/") if part]
	return pascal_case(parts[-1] if parts else "ApiResponse")


def linked_endpoints(value: Any) -> list[str]:
	if not isinstance(value, dict):
		return []
	results = value.get("results")
	if not isinstance(results, list):
		return []
	return [
		item["url"]
		for item in results
		if isinstance(item, dict) and isinstance(item.get("url"), str)
	]


def collection_endpoints(value: Any) -> list[str]:
	if not isinstance(value, dict):
		return []
	return [endpoint for endpoint in value.values() if isinstance(endpoint, str) and endpoint.startswith("/")]


def api_url(value: Any) -> str | None:
	if not isinstance(value, str):
		return None
	url = absolute_url(value)
	return url if url.startswith(URL_BASE) else None


def hydrate_urls(
	value: Any,
	session: requests.Session,
	visited: set[str],
	*,
	current_url: str | None = None,
) -> Any:
	"""Replace nested API references with merged, recursively hydrated payloads."""
	if isinstance(value, list):
		return [hydrate_urls(item, session, visited, current_url=current_url) for item in value]
	if not isinstance(value, dict):
		return value

	reference_url = api_url(value.get("url"))
	if reference_url and reference_url != current_url and reference_url not in visited:
		visited.add(reference_url)
		detail = fetch_json(session, reference_url)
		merged = {**value, **detail}
		return hydrate_urls(
			merged,
			session,
			visited,
			current_url=reference_url,
		)

	return {
		key: hydrate_urls(child, session, visited, current_url=current_url)
		for key, child in value.items()
	}


def build_module(endpoint: str, recursive: bool) -> str:
	session = requests.Session()
	builder = DataclassBuilder()
	visited: set[str] = set()
	queue = [endpoint]

	while queue:
		current = queue.pop(0)
		absolute = urljoin(URL_BASE, current.lstrip("/"))
		if absolute in visited or not absolute.startswith(URL_BASE):
			continue
		visited.add(absolute)
		payload = fetch_json(session, absolute)
		if recursive:
			payload = hydrate_urls(payload, session, visited, current_url=absolute)
		builder.add_value(endpoint_name(absolute), payload)
		if absolute == URL_BASE:
			queue.extend(collection_endpoints(payload))
		elif recursive:
			queue.extend(linked_endpoints(payload))

	lines = [
		GEN_WARNING,
		"from __future__ import annotations",
		"",
		"from dataclasses import dataclass, field",
		"from typing import Any",
		"",
		"",
	]
	for definition in builder.definitions:
		lines.append("@dataclass")
		lines.append(f"class {definition.name}:")
		if not definition.fields:
			lines.append("    pass")
		else:
			for field_name, type_name, original_key in definition.fields:
				metadata = "" if field_name == original_key else f' = field(metadata={{"json_key": "{original_key}"}})'
				lines.append(f"    {field_name}: {type_name}{metadata}")
		lines.extend(["", ""])
	return "\n".join(lines).rstrip() + "\n"


def parse_args() -> argparse.Namespace:
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("--endpoint", default="", help="API path or URL to generate")
	parser.add_argument(
		"--no-recursive",
		action="store_true",
		help="Generate from the selected response without fetching nested API URLs",
	)
	parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Generated Python file")
	return parser.parse_args()


def main() -> None:
	args = parse_args()
	output = build_module(args.endpoint, recursive=not args.no_recursive)
	args.output.write_text(output, encoding="utf-8")
	print(f"Generated {args.output} from {urljoin(URL_BASE, args.endpoint)}")


if __name__ == "__main__":
	main()



