# This file is auto-generated by api.build_importer. Do not edit manually.

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class ApiResponse:
    ability_scores: str = field(metadata={"json_key": "ability-scores"})
    alignments: str
    backgrounds: str
    classes: str
    conditions: str
    damage_types: str = field(metadata={"json_key": "damage-types"})
    equipment: str
    equipment_categories: str = field(metadata={"json_key": "equipment-categories"})
    feats: str
    features: str
    languages: str
    magic_items: str = field(metadata={"json_key": "magic-items"})
    magic_schools: str = field(metadata={"json_key": "magic-schools"})
    monsters: str
    proficiencies: str
    races: str
    rule_sections: str = field(metadata={"json_key": "rule-sections"})
    rules: str
    skills: str
    spells: str
    subclasses: str
    subraces: str
    traits: str
    weapon_properties: str = field(metadata={"json_key": "weapon-properties"})


@dataclass
class AbilityScores:
    count: int
    results: list[AbilityScoresResultsItem]


@dataclass
class AbilityScoresResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Alignments:
    count: int
    results: list[AlignmentsResultsItem]


@dataclass
class AlignmentsResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Backgrounds:
    count: int
    results: list[BackgroundsResultsItem]


@dataclass
class BackgroundsResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Classes:
    count: int
    results: list[ClassesResultsItem]


@dataclass
class ClassesResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Conditions:
    count: int
    results: list[ConditionsResultsItem]


@dataclass
class ConditionsResultsItem:
    index: str
    name: str
    url: str


@dataclass
class DamageTypes:
    count: int
    results: list[DamageTypesResultsItem]


@dataclass
class DamageTypesResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Equipment:
    count: int
    results: list[EquipmentResultsItem]


@dataclass
class EquipmentResultsItem:
    index: str
    name: str
    url: str


@dataclass
class EquipmentCategories:
    count: int
    results: list[EquipmentCategoriesResultsItem]


@dataclass
class EquipmentCategoriesResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Feats:
    count: int
    results: list[FeatsResultsItem]


@dataclass
class FeatsResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Features:
    count: int
    results: list[FeaturesResultsItem]


@dataclass
class FeaturesResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Languages:
    count: int
    results: list[LanguagesResultsItem]


@dataclass
class LanguagesResultsItem:
    index: str
    name: str
    url: str


@dataclass
class MagicItems:
    count: int
    results: list[MagicItemsResultsItem]


@dataclass
class MagicItemsResultsItem:
    index: str
    name: str
    url: str


@dataclass
class MagicSchools:
    count: int
    results: list[MagicSchoolsResultsItem]


@dataclass
class MagicSchoolsResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Monsters:
    count: int
    results: list[MonstersResultsItem]


@dataclass
class MonstersResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Proficiencies:
    count: int
    results: list[ProficienciesResultsItem]


@dataclass
class ProficienciesResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Races:
    count: int
    results: list[RacesResultsItem]


@dataclass
class RacesResultsItem:
    index: str
    name: str
    url: str


@dataclass
class RuleSections:
    count: int
    results: list[RuleSectionsResultsItem]


@dataclass
class RuleSectionsResultsItem:
    name: str
    index: str
    url: str


@dataclass
class Rules:
    count: int
    results: list[RulesResultsItem]


@dataclass
class RulesResultsItem:
    name: str
    index: str
    url: str


@dataclass
class Skills:
    count: int
    results: list[SkillsResultsItem]


@dataclass
class SkillsResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Spells:
    count: int
    results: list[SpellsResultsItem]


@dataclass
class SpellsResultsItem:
    index: str
    name: str
    level: int
    url: str


@dataclass
class Subclasses:
    count: int
    results: list[SubclassesResultsItem]


@dataclass
class SubclassesResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Subraces:
    count: int
    results: list[SubracesResultsItem]


@dataclass
class SubracesResultsItem:
    index: str
    name: str
    url: str


@dataclass
class Traits:
    count: int
    results: list[TraitsResultsItem]


@dataclass
class TraitsResultsItem:
    index: str
    name: str
    url: str


@dataclass
class WeaponProperties:
    count: int
    results: list[WeaponPropertiesResultsItem]


@dataclass
class WeaponPropertiesResultsItem:
    index: str
    name: str
    url: str
